In [1]:
print("Hello")
print('sandy')
print(123)

Hello
sandy
123


In [15]:
for i in range(10):
    print(i)

0
1
2
3
4
5
6
7
8
9


In [17]:
name = 'Sandya'
print(name)

Sandya


In [25]:
var1 = 123
var1 = 223

In [27]:
var1

223

In [57]:
var = 1
var

1

In [59]:
Var = 2
Var

2

In [37]:
2var ='sandy'
2var

SyntaxError: invalid decimal literal (586531444.py, line 1)

In [45]:
_var_string_=1
_var_string_

1

In [63]:
sandy = 'name'
sandy

'name'

In [67]:
sandy = 'love her'
sandy

'love her'

In [69]:
sandy

'love her'

In [ ]:
# text type 
' '," ",""" """,''' '''

In [75]:
var1='sandy'
var2="sandy"
print(var1,var2)

sandy sandy


In [77]:
str = "hello everyone"
print(str)

hello everyone


In [93]:
str1 = '''hello Im sandya
learning python
I will successed in my career so Im grateful for everything
thank you for choosing the career'''
print(str1)

hello Im sandya
learning python
I will successed in my career so Im grateful for everything
thank you for choosing the career


In [91]:
str2 = """Each day is new beginning. I should not think about the past. 
everybody thinks that im not successed in career. Im going to acive my goals,
one my first name enough to recognise my name.
"""
print(str2)

Each day is new beginning. I should not think about the past. 
everybody thinks that im not successed in career. Im going to acive my goals,
one my first name enough to recognise my name.



In [95]:
str3 = 'sandy "loves momos"'
print(str3)

sandy "loves momos"


In [97]:
type(str3)

str

In [99]:
#Numeric type
#int +,-,0
int1 = 456
int1

456

In [101]:
int2 = -234
int2

-234

In [103]:
int3 = 0
int3

0

In [113]:
type(int1)

int

In [115]:
#float
fl = 12.06
fl

12.06

In [117]:
type(fl)

float

In [121]:
a,b,c,d = 10,23.675,-23,0.98

In [127]:
type(d)

float

In [129]:
type(c)

int

In [131]:
type(b)

float

In [133]:
type(a)

int

In [135]:
#Complex=real+imaginary number
com = 12+1j
print(com)

(12+1j)


In [137]:
type(com)

complex

In [139]:
com2 = 12j+56
com2

(56+12j)

In [141]:
print(com2)

(56+12j)


In [ ]:
# Operators
# 1.arithematic operators


In [183]:
x,y,z = 5,15,20
sum = x+y+z
divide = x/y
sub = x-z
subb = x//y
power = x**y
mod = x%y
print(sum)
print(divide)
print(sub)
print(subb)
print(power)
print(mod)

40
0.3333333333333333
-15
0
30517578125
5


In [ ]:
# 2.assignment operators

In [175]:
x=x+2
x

7

In [177]:
y=y-2
y

13

In [179]:
z=z/5
z

4.0

In [185]:
x+=3
x

8

In [187]:
y-=2
y

13

In [ ]:
# 3.comparision operators

In [189]:
a,b

(10, 23.675)

In [191]:
print(a==b)

False


In [193]:
print(a!=b)

True


In [195]:
print(a>b)

False


In [199]:
print(a<b)

True


In [201]:
print(a>=b)

False


In [203]:
print(a<=b)

True


In [205]:
x = 'Iam sandya, who love gardning'
print('love' in x)

True


In [209]:
print('great' not in x)

True


In [213]:
a = 123
b = 234
c=123

In [217]:
a is b

False

In [219]:
b is a 

False

In [221]:
b is b

True

In [223]:
b is c

False

In [225]:
c is a 

True

In [227]:
a is c

True

In [229]:
b is not a

True

In [231]:
b is not b

False

In [1]:
# list
list1 = [1,4,5,6,7,3,8,9,10]
list1

(1, 4, 5, 6, 7, 3, 8, 9, 10)

In [5]:
list1[2]

5

In [7]:
tuple = (1,4,2,5,8,6,4)
tuple

(1, 4, 2, 5, 8, 6, 4)

In [9]:
tuple[5]

6

In [11]:
s={1,4,8,30,20,60,15,3,1,6,8}
s

{1, 3, 4, 6, 8, 15, 20, 30, 60}

In [21]:
list1=[1,2,3,5,4,True,False,'sandy','geetha',(1,2,3,6)]
list1

[1, 2, 3, 5, 4, True, False, 'sandy', 'geetha', (1, 2, 3, 6)]

In [23]:
list1[3]=15

In [25]:
list1

[1, 2, 3, 15, 4, True, False, 'sandy', 'geetha', (1, 2, 3, 6)]

In [27]:
list1 =[[1,2,3,4],[True,False],['sandy','shashi']]
list1

[[1, 2, 3, 4], [True, False], ['sandy', 'shashi']]

In [31]:
list1[2]

['sandy', 'shashi']

In [33]:
l=[1,2,4,5,6,7,8,8,9,10]
l

[1, 2, 4, 5, 6, 7, 8, 8, 9, 10]

In [35]:
l[2:6]

[4, 5, 6, 7]

In [37]:
l[:6]

[1, 2, 4, 5, 6, 7]

In [39]:
len(l)-1

9

In [43]:
len(l)-2

8

In [45]:
l[::-1]

[10, 9, 8, 8, 7, 6, 5, 4, 2, 1]

In [47]:
type(l)

list

In [49]:
l

[1, 2, 4, 5, 6, 7, 8, 8, 9, 10]

In [51]:
l.append(2)

In [53]:
l

[1, 2, 4, 5, 6, 7, 8, 8, 9, 10, 2]

In [55]:
l.insert(3,10)

In [57]:
l

[1, 2, 4, 10, 5, 6, 7, 8, 8, 9, 10, 2]

In [59]:
l.remove(2)

In [61]:
l

[1, 4, 10, 5, 6, 7, 8, 8, 9, 10, 2]

In [63]:
l.remove(8)

In [65]:
l

[1, 4, 10, 5, 6, 7, 8, 9, 10, 2]

In [69]:
l.sort()

In [71]:
l

[1, 2, 4, 5, 6, 7, 8, 9, 10, 10]

In [73]:
l.sort(reverse=True)

In [75]:
l

[10, 10, 9, 8, 7, 6, 5, 4, 2, 1]

In [1]:
n1 = int(input("Enter the first number"))
n2 = int(input("Enter the seconds number"))
n_count = int(input("Enter the count"))
count = 0
print(n1)
print(n2)
while count<n_count:
    next=n1+n2
    print(next)
    n1=n2
    n2=next
    count=count+1

Enter the first number 2
Enter the seconds number 5
Enter the count 2


2
5
7
12


In [3]:
n1 = int(input("Enter the first number"))
n2 = int(input("Enter the seconds number"))
n_count=int(input("Enter the count"))
count=0
print(n1)
print(n2)
while count<n_count:
    next=n1+n2
    print(next)
    n1=n2
    n2=next
    count=count+1

Enter the first number 2
Enter the seconds number 5
Enter the count 2


2
5
7
12


In [5]:
set1 = {2,5,4,6,3,5,6}
set2 = {2,5,3,1,7,9,10}
set1.union(set2)

{1, 2, 3, 4, 5, 6, 7, 9, 10}

In [9]:
set1.intersection(set2)

{2, 3, 5}

In [19]:
dict1 = {'name':'sandy','age':25,'brgoup':'b+'}
dict1

{'name': 'sandy', 'age': 25, 'brgoup': 'b+'}

In [25]:
dict1.keys()

dict_keys(['name', 'age', 'brgoup'])

In [28]:
dict1.values()

dict_values(['sandy', 25, 'b+'])

In [32]:
dict1.items()

dict_items([('name', 'sandy'), ('age', 25), ('brgoup', 'b+')])

In [3]:
# if else
x,y=10,25
if x>y:
    print(f'{x} is greater than {y}')
else:
    print(f'{y} is greater than {x}')

25 is greater than 10


In [15]:
x,y,z = 10,2,15
if x<y:
    print(f'{x} is greater than {y}')
elif x<z:
    print(f'{z} is greater than {x}')
else:
    print(f'{x} is greater than {y} and {z}')

15 is greater than 10


In [19]:
x = int(input("Enter a number"))
if x>0:
    if x%2==0:
        print(f'{x} is even')
    else:
        print(f'{x} is odd')
else:
    print(f'{x} is positive number')

Enter a number 5


5 is odd


In [21]:
x = int(input("Enter a number"))
if x>0:
    if x%2==0:
        print(f'{x} is even')
    else:
        print(f'{x} is odd')
else:
    print(f'{x} is positive number')

Enter a number 8


8 is even


In [23]:
x = int(input("Enter a number"))
if x>0:
    if x%2==0:
        print(f'{x} is even')
    else:
        print(f'{x} is odd')
else:
    print(f'{x} is positive number')

Enter a number 0


0 is positive number


In [25]:
l = [1,4,5,6,7,7,38,12,3,54,65,57]
for i in l:
    print(f'{i} is l')

1 is l
4 is l
5 is l
6 is l
7 is l
7 is l
38 is l
12 is l
3 is l
54 is l
65 is l
57 is l


In [27]:
l = [1,4,5,6,7,7,38,12,3,54,65,57]
for i in l:
    print(f'{i}')

1
4
5
6
7
7
38
12
3
54
65
57


In [37]:
for i in range(len(l)):
    print(f'loop {i+1}:{l[i]}')

loop 1:1
loop 2:4
loop 3:5
loop 4:6
loop 5:7
loop 6:7
loop 7:38
loop 8:12
loop 9:3
loop 10:54
loop 11:65
loop 12:57


In [45]:
count = 0
for i in l:
    if i>5:
        count+=1
print(count)

8


In [49]:
count=0
if i in l:
    if x>6:
        count+=0
print(count)

0


In [53]:
list=[[1,2,3,4],[5,4,3,8,10]]
for x in list:
    for y in x:
        print(y)

1
2
3
4
5
4
3
8
10


In [1]:
#while
x=3
while x>0:
    print(x)
    x-=1

3
2
1


In [3]:
#while
x=5
while x>0:
    print(x)
    x-=2

5
3
1


In [5]:
x=5
while x>0:
    print(x)
    x-=1

5
4
3
2
1


In [7]:
sum=0
while sum<15:
    sum=sum+1
print(sum)

15


In [1]:
sum=19
while sum<25:
    sum=sum+1
print(sum)

25


In [3]:
list1=[3,5, 12, 3, 2, 1]

In [7]:
for x in list1:
    if x%2==0:
        break
    else:
        print(x)

3
5


In [5]:
for x in list1:
    if x%2==0:
        break
    else:
        print(x)

count=0
for x in list1:
    if x>5:
        count+=1
print(count)

3
5
1


In [11]:
def function_c():
    print("hello")
function_c()

hello


In [15]:
def sum():
    x=10
    y=20
    return x+y
sum()

30

In [19]:
z=sum()
print(z)

30


In [25]:
def sum(n1,n2):
    total = n1+n2
    return total
sum(100,566)

666

In [29]:
print(sum(2,3))
print(sum(3,4))

5
7


In [39]:
def allodd_beforeeven(list1):
    for x in list1:
        if x%2==0:
            break
        else:
            print( x)
def count_greater5(list1):
    count = 0
    for x in list1:
        if x>5:
            count+=1
print(count)

1


In [43]:
x=[1,2,4,5,56,4]
allodd_beforeeven(x)
count_greater5(x)

1


In [7]:
n = int(input("enter a number"))
s=str(n)
power=len(s)
sum=0
for i in s:
    sum+=int(i)**power
if n==sum:
    print(f'{n} is armstrong number')
else:
    print(f'{n} is not a armstrong number')

enter a number 5


5 is armstrong number


In [15]:
n = int(input("Enter a number"))
for i in range(2,n):
    if n%i==0:
        print(f'{n} is not a prime')
        break
else:
    print(f"{n}is a prime")

Enter a number 2


2is a prime


In [5]:
list=[1,5,4,6,7,8.10,20,20]
max(list)

20

In [7]:
min(list)

1

In [9]:
n = int(input("enter a number"))
list=[1,5,4,6,7,8.10,20,20]
if(n>max(list)):
    print(f'{n} is greater')
else:
    print(f'{n} is lower')

enter a number 8


8 is lower


In [11]:
list = []
for i in range(1,51):
    list.append(2*i)

In [27]:
list

[2,
 4,
 6,
 8,
 10,
 12,
 14,
 16,
 18,
 20,
 22,
 24,
 26,
 28,
 30,
 32,
 34,
 36,
 38,
 40,
 42,
 44,
 46,
 48,
 50,
 52,
 54,
 56,
 58,
 60,
 62,
 64,
 66,
 68,
 70,
 72,
 74,
 76,
 78,
 80,
 82,
 84,
 86,
 88,
 90,
 92,
 94,
 96,
 98,
 100]

In [35]:
list1 =[2*i for i in range(2,50)]
list1

[4,
 6,
 8,
 10,
 12,
 14,
 16,
 18,
 20,
 22,
 24,
 26,
 28,
 30,
 32,
 34,
 36,
 38,
 40,
 42,
 44,
 46,
 48,
 50,
 52,
 54,
 56,
 58,
 60,
 62,
 64,
 66,
 68,
 70,
 72,
 74,
 76,
 78,
 80,
 82,
 84,
 86,
 88,
 90,
 92,
 94,
 96,
 98]

In [37]:
# Count the number of elements in the list.
len(list)

50

In [39]:
#Reverse the sequence of the list.
list[::-1]

[100,
 98,
 96,
 94,
 92,
 90,
 88,
 86,
 84,
 82,
 80,
 78,
 76,
 74,
 72,
 70,
 68,
 66,
 64,
 62,
 60,
 58,
 56,
 54,
 52,
 50,
 48,
 46,
 44,
 42,
 40,
 38,
 36,
 34,
 32,
 30,
 28,
 26,
 24,
 22,
 20,
 18,
 16,
 14,
 12,
 10,
 8,
 6,
 4,
 2]

In [41]:
#Sort the list in ascending and descending order
list.sort()


In [47]:
Get the index value for the element 44, and update the element with the number
100.
n=list.index(44)
n

21

In [17]:
# Return a copy of the list, with the resulting list containing the square of each element.
s_list=[]
for x in list:
    s_list.append(x**2)

In [19]:
s_list

[4,
 16,
 36,
 64,
 100,
 144,
 196,
 256,
 324,
 400,
 484,
 576,
 676,
 784,
 900,
 1024,
 1156,
 1296,
 1444,
 1600,
 1764,
 1936,
 2116,
 2304,
 2500,
 2704,
 2916,
 3136,
 3364,
 3600,
 3844,
 4096,
 4356,
 4624,
 4900,
 5184,
 5476,
 5776,
 6084,
 6400,
 6724,
 7056,
 7396,
 7744,
 8100,
 8464,
 8836,
 9216,
 9604,
 10000]

In [61]:
s_list=[x**2 for x in list ]
s_list

[4,
 16,
 36,
 64,
 100,
 144,
 196,
 256,
 324,
 400,
 484,
 576,
 676,
 784,
 900,
 1024,
 1156,
 1296,
 1444,
 1600,
 1764,
 1936,
 2116,
 2304,
 2500,
 2704,
 2916,
 3136,
 3364,
 3600,
 3844,
 4096,
 4356,
 4624,
 4900,
 5184,
 5476,
 5776,
 6084,
 6400,
 6724,
 7056,
 7396,
 7744,
 8100,
 8464,
 8836,
 9216,
 9604,
 10000]

In [3]:
import numpy as np
a = np.array([1,2,3])
a

array([1, 2, 3])

In [5]:
b=np.array([[1,2,3],[12,34,15]])
b

array([[ 1,  2,  3],
       [12, 34, 15]])

In [7]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [9]:
np.zeros((1,2))

array([[0., 0.]])

In [11]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [13]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [19]:
np.arange(10,20,2)

array([10, 12, 14, 16, 18])

In [15]:
np.linspace(5,10,10)

array([ 5.        ,  5.55555556,  6.11111111,  6.66666667,  7.22222222,
        7.77777778,  8.33333333,  8.88888889,  9.44444444, 10.        ])

In [21]:
np.linspace(0,10,6)

array([ 0.,  2.,  4.,  6.,  8., 10.])

In [23]:
np.full((2,3),6)

array([[6, 6, 6],
       [6, 6, 6]])

In [27]:
np.full((3,3),5)

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

In [29]:
np.random.random((2,3))

array([[0.8755631 , 0.04598577, 0.16821306],
       [0.93275866, 0.58993455, 0.05028155]])

In [31]:
np.random.random((3,3))

array([[1.91746063e-01, 5.18279808e-01, 1.64536354e-01],
       [5.43277906e-01, 8.51374601e-01, 3.33715303e-04],
       [8.62882117e-01, 9.10842811e-01, 7.94320228e-01]])

a=np.array([[2,3,4],[3,4,5]])
a.shape=(3,2)
print(a)

In [63]:
a=np.array([[1,2,3],[4,5,6],[1,2,3]])
a.shape=(9,1)
print(a)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [1]
 [2]
 [3]]


In [65]:
a=np.array([[2,3,4],[3,4,5]])
a.shape=(3,2)
print(a)

[[2 3]
 [4 3]
 [4 5]]


In [67]:
a=np.arange(24)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [71]:
print(a.ndim)

1


In [73]:
b=a.reshape(2,4,3)
print(b.ndim)

3


In [75]:
print(a.size)

24


In [77]:
print(b.size)

24


In [79]:
a=np.arange(24,dtype=float)
print(a.dtype)
a

float64


array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,
       13., 14., 15., 16., 17., 18., 19., 20., 21., 22., 23.])

In [81]:
np.sum([10,20])

30

In [83]:
a,b=10,20
np.sum([a,b])

30

In [87]:
np.subtract(a,b)

-10

In [89]:
np.divide(a,b)

0.5

In [91]:
np.multiply(a,b)

200

In [93]:
print("Exponent:", np.exp(a))
print("Square root:", np.sqrt(a))
print("Sin:", np.sin(a))
print("cos:", np.cos(a))
print("log:", np.log(a))

Exponent: 22026.465794806718
Square root: 3.1622776601683795
Sin: -0.5440211108893698
cos: -0.8390715290764524
log: 2.302585092994046


In [99]:
a=[1,2,3]
b=[2,3,4]
c=[1,2,3]
np.equal(a,b)

array([False, False, False])

In [101]:
np.equal(a,c)

array([ True,  True,  True])

In [105]:
np.equal(b,c)

array([False, False, False])

In [107]:
np.array_equal(a,b)

False

In [109]:
np.array_equal(b,c)

False

In [111]:
np.array_equal(a,c)

True