In [3]:
#IMPORTING THE NECESSARY LIBRARY
import numpy as np

In [27]:
# 1D array

val = np.array([1,2,3,4,5])
print(val)
print(val.dtype) #returns the datatype of the array
print(val.shape) #returns shape of the array
print(val.ndim) #returns dimension of the array

[1 2 3 4 5]
int32
(5,)
1


In [29]:
# 2D array

val1 = np.array([[1,2,3,4,5],[10,20,30,40,50]])
print(val1)
print(val1.dtype) #returns the datatype of the array
print(val1.shape) #returns shape of the array
print(val1.ndim) #returns dimension of the array

[[ 1  2  3  4  5]
 [10 20 30 40 50]]
int32
(2, 5)
2


In [39]:
# 3D array

val3 = np.array([[[1,2,3,4,5],[10,20,30,40,50]]], dtype=float) #changed the dtype to float
print(val3)
print(val3.dtype) #returns the datatype of the array
print(val3.shape) #returns shape of the array
print(val3.ndim) #returns dimension of the array

[[[ 1.  2.  3.  4.  5.]
  [10. 20. 30. 40. 50.]]]
float64
(1, 2, 5)
3


In [43]:
# 4D array

val4 = np.array([[[[1,2,3,4,5],[10,20,30,40,50]]]], dtype=float) #changed the dtype to float
print(val4)
print(val4.dtype) #returns the datatype of the array
print(val4.shape) #returns shape of the array
print(val4.ndim) #returns dimension of the array

[[[[ 1.  2.  3.  4.  5.]
   [10. 20. 30. 40. 50.]]]]
float64
(1, 1, 2, 5)
4


In [63]:
#Created a numpy array with numpy.array module and with a data type integer and float.

n = np.array([10,20,30,40],dtype = float)
print(n)
n1 = np.array([10,20,30,40],dtype = int)
print(n1)

[10. 20. 30. 40.]
[10 20 30 40]


In [75]:
#Created a 2x2, 3x3, and 4x4 identity matrix using numpy.

arr = np.identity(2, dtype = int) #2x2
print(arr)

[[1 0]
 [0 1]]


In [77]:
arr1 = np.identity(3, dtype = int) #3x3
print(arr1)

[[1 0 0]
 [0 1 0]
 [0 0 1]]


In [79]:
arr2 = np.identity(4, dtype = int) #4x4
print(arr2)

[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]


In [89]:
#Created a numpy array with shape 2x5 that has all the elements as zero.

np.zeros((2,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [91]:
np.zeros(10).reshape(2,5)

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [93]:
#Created a numpy array that has the shape 3x5 and all the elements are 5.

np.full([3,5],5)

array([[5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5]])

In [95]:
#Created a numpy array with random integers in the range 0-100, and the sample size should be 25.

np.random.randint(0,100,25)

array([90, 90, 82, 70, 97, 42, 10, 19, 56, 50,  7, 39, 27, 43, 91, 53, 60,
       22, 74, 54, 45, 51, 26,  9, 66])

In [97]:
#Created a numpy array with a shape 3x3 that has all elements as 1

np.full((3,3),1)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [99]:
#Created a numpy array with a shape 3x3 that has all elements as 'letter'

np.full((3,3),'letter')

array([['letter', 'letter', 'letter'],
       ['letter', 'letter', 'letter'],
       ['letter', 'letter', 'letter']], dtype='<U6')

In [105]:
#Addition using numpy

np.sum([1,2,4])

30

In [129]:
a = 10
b = 20
print('Sum :', np.sum([a,b]))
print('Subract :', np.subtract(a,b))
print('Multiply : ', np.multiply(a,b))
print('Divid : ', np.divide(a,b))

Sum : 30
Subract : -10
Multiply :  200
Divid :  0.5


In [135]:
#Mathematic Function

a = 10
print('Exponent:' , np.exp(a))
print('Square root:', np.sqrt(a))
print('Sin:', np.sin(a))
print('Cos:', np.cos(a))
print('Log:', np.log(a))

Exponent: 22026.465794806718
Square root: 3.1622776601683795
Sin: -0.5440211108893698
Cos: -0.8390715290764524
Log: 2.302585092994046


In [9]:
#Array Comparision

a = np.array([1,2,3,4,5])
b = np.array([3,5,6,7,7])
c = np.array([1,2,3,4,5])
print('Comparing a and b: ',np.equal(a,b))
print('Comparing a and c: ',np.equal(a,c))
print('Comparing c and b: ',np.equal(a,b))

Comparing a and b:  [False False False False False]
Comparing a and c:  [ True  True  True  True  True]
Comparing c and b:  [False False False False False]


In [11]:
# Aggregate Function

arr1 = np.array([1,2,4])

print(f"Sum : {np.sum(arr1)}")
print(f"Minimum Value : {np.min(arr1)}")
print(f"Maximum Value : {np.max(arr1)}")
print(f"Mean Value : {np.mean(arr1)}")
print(f"Median Value : {np.median(arr1)}")
print(f"Variance : {np.var(arr1)}")
print(f"Std Dev : {np.std(arr1)}")

Sum : 7
Minimum Value : 1
Maximum Value : 4
Mean Value : 2.3333333333333335
Median Value : 2.0
Variance : 1.5555555555555554
Std Dev : 1.247219128924647


In [21]:
#Slicing

x = np.array(['Sandy','Prabhu','Nayana','Santosh','Lalitha','Rudra','Toby'])
x[2:4]

array(['Nayana', 'Santosh'], dtype='<U7')

In [23]:
x[0:3]

array(['Sandy', 'Prabhu', 'Nayana'], dtype='<U7')

In [25]:
#Concatenate

x = ([1,2,3,4,5,6])
y = ([2,3,4,5,7,8])

np.concatenate([x,y])

array([1, 2, 3, 4, 5, 6, 2, 3, 4, 5, 7, 8])

In [29]:
# vertical stack

arr1 = np.array([[1,2],[4,5]])
arr2 = np.array([[2,2],[10,10]])
print('Vertical Stack:', np.vstack([arr1,arr2]))
print('Horizantal Stack:', np.hstack([arr1,arr2]))  #Horizontal stack

Vertical Stack: [[ 1  2]
 [ 4  5]
 [ 2  2]
 [10 10]]
Horizantal Stack: [[ 1  2  2  2]
 [ 4  5 10 10]]
